# config.yaml
salesforce:
  # Use test.salesforce.com for Sandboxes, login.salesforce.com for Production.
  login_domain: "test.salesforce.com"
  client_id: "YOUR_SALESFORCE_CONSUMER_KEY"
  client_secret: "YOUR_SALESFORCE_CONSUMER_SECRET"

  # The SOQL query to execute.
  # Use {{.WhereClause}} as a placeholder for date and modification filters.
  # Ensure all fields for CoreFields (Id, Name, Amount, CloseDate, LastModifiedDate) are included.
  query: >-
    SELECT
      Id, Name, Amount, CloseDate, LastModifiedDate, Payout_Reference__c,
      StageName, RecordType.Name, Account.Name,
      CreatedBy.Name, CreatedDate, LastModifiedBy.Name
    FROM Opportunity
    WHERE {{.WhereClause}}

  # Optional: field_mappings map API field names from the query to user-friendly
  # local names. There are optional additional fields to show in the UI via
  # templates and are not easily searchable as part of the core
  # Opportunity/Donation object. These are in AdditionalFields map for use in
  # templates.
  #
  # Note: Nested object names are represented with a dot (".") as in Account.Name.
  field_mappings:
    StageName: Stage
    Account.Name: Account
    CreatedBy.Name: CreatedBy
    LastModifiedBy.Name: ModifiedBy

  # linking_object and linking_field_name are the object and field name
  # to target for distributed foreign key (DFK) updates. It is very
  # important that the "id" in BatchUpdateOpportunityRefs (client.go)
  # accords with the object specified here.
  linking_object: "Opportunity"
  linking_field_name: "Payout_Reference__c"

# Default paths used by the application
token_file_path: "./sf_token.json"
database_path: "./reconciliation.db"

# Default date range start (YYYY-MM-DD) for fetching records.
date_range_start: "2025-04-01"
